package org.nightang.db.stock.model;

import java.util.Date;

public class PatternResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATTERN_RESULT.PATTERN_TYPE
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    private String patternType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATTERN_RESULT.STOCK_NUM
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    private String stockNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATTERN_RESULT.STOCK_DATE
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    private Date stockDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATTERN_RESULT.FLAG_H_VOLUME
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    private Double flagHVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATTERN_RESULT.LAST_MODIFIED_DATE
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    private Date lastModifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATTERN_RESULT.PATTERN_TYPE
     *
     * @return the value of PATTERN_RESULT.PATTERN_TYPE
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    public String getPatternType() {
        return patternType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATTERN_RESULT.PATTERN_TYPE
     *
     * @param patternType the value for PATTERN_RESULT.PATTERN_TYPE
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    public void setPatternType(String patternType) {
        this.patternType = patternType == null ? null : patternType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATTERN_RESULT.STOCK_NUM
     *
     * @return the value of PATTERN_RESULT.STOCK_NUM
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    public String getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATTERN_RESULT.STOCK_NUM
     *
     * @param stockNum the value for PATTERN_RESULT.STOCK_NUM
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    public void setStockNum(String stockNum) {
        this.stockNum = stockNum == null ? null : stockNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATTERN_RESULT.STOCK_DATE
     *
     * @return the value of PATTERN_RESULT.STOCK_DATE
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    public Date getStockDate() {
        return stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATTERN_RESULT.STOCK_DATE
     *
     * @param stockDate the value for PATTERN_RESULT.STOCK_DATE
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    public void setStockDate(Date stockDate) {
        this.stockDate = stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATTERN_RESULT.FLAG_H_VOLUME
     *
     * @return the value of PATTERN_RESULT.FLAG_H_VOLUME
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    public Double getFlagHVolume() {
        return flagHVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATTERN_RESULT.FLAG_H_VOLUME
     *
     * @param flagHVolume the value for PATTERN_RESULT.FLAG_H_VOLUME
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    public void setFlagHVolume(Double flagHVolume) {
        this.flagHVolume = flagHVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATTERN_RESULT.LAST_MODIFIED_DATE
     *
     * @return the value of PATTERN_RESULT.LAST_MODIFIED_DATE
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATTERN_RESULT.LAST_MODIFIED_DATE
     *
     * @param lastModifiedDate the value for PATTERN_RESULT.LAST_MODIFIED_DATE
     *
     * @mbg.generated Thu May 25 15:10:59 CST 2017
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}