package org.nightang.db.stock.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StockPriceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public StockPriceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> stockDateCriteria;

        protected List<Criterion> lastModifiedDateCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            stockDateCriteria = new ArrayList<Criterion>();
            lastModifiedDateCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getStockDateCriteria() {
            return stockDateCriteria;
        }

        protected void addStockDateCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            stockDateCriteria.add(new Criterion(condition, value, "org.nightang.db.mybatis.DateOnlyToTextTypeHandler"));
            allCriteria = null;
        }

        protected void addStockDateCriterion(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            stockDateCriteria.add(new Criterion(condition, value1, value2, "org.nightang.db.mybatis.DateOnlyToTextTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getLastModifiedDateCriteria() {
            return lastModifiedDateCriteria;
        }

        protected void addLastModifiedDateCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            lastModifiedDateCriteria.add(new Criterion(condition, value, "org.nightang.db.mybatis.DateToTextTypeHandler"));
            allCriteria = null;
        }

        protected void addLastModifiedDateCriterion(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            lastModifiedDateCriteria.add(new Criterion(condition, value1, value2, "org.nightang.db.mybatis.DateToTextTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || stockDateCriteria.size() > 0
                || lastModifiedDateCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(stockDateCriteria);
                allCriteria.addAll(lastModifiedDateCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andStockNumIsNull() {
            addCriterion("STOCK_NUM is null");
            return (Criteria) this;
        }

        public Criteria andStockNumIsNotNull() {
            addCriterion("STOCK_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andStockNumEqualTo(String value) {
            addCriterion("STOCK_NUM =", value, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumNotEqualTo(String value) {
            addCriterion("STOCK_NUM <>", value, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumGreaterThan(String value) {
            addCriterion("STOCK_NUM >", value, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumGreaterThanOrEqualTo(String value) {
            addCriterion("STOCK_NUM >=", value, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumLessThan(String value) {
            addCriterion("STOCK_NUM <", value, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumLessThanOrEqualTo(String value) {
            addCriterion("STOCK_NUM <=", value, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumLike(String value) {
            addCriterion("STOCK_NUM like", value, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumNotLike(String value) {
            addCriterion("STOCK_NUM not like", value, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumIn(List<String> values) {
            addCriterion("STOCK_NUM in", values, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumNotIn(List<String> values) {
            addCriterion("STOCK_NUM not in", values, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumBetween(String value1, String value2) {
            addCriterion("STOCK_NUM between", value1, value2, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockNumNotBetween(String value1, String value2) {
            addCriterion("STOCK_NUM not between", value1, value2, "stockNum");
            return (Criteria) this;
        }

        public Criteria andStockDateIsNull() {
            addCriterion("STOCK_DATE is null");
            return (Criteria) this;
        }

        public Criteria andStockDateIsNotNull() {
            addCriterion("STOCK_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andStockDateEqualTo(Date value) {
            addStockDateCriterion("STOCK_DATE =", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateNotEqualTo(Date value) {
            addStockDateCriterion("STOCK_DATE <>", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateGreaterThan(Date value) {
            addStockDateCriterion("STOCK_DATE >", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateGreaterThanOrEqualTo(Date value) {
            addStockDateCriterion("STOCK_DATE >=", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateLessThan(Date value) {
            addStockDateCriterion("STOCK_DATE <", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateLessThanOrEqualTo(Date value) {
            addStockDateCriterion("STOCK_DATE <=", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateLike(Date value) {
            addStockDateCriterion("STOCK_DATE like", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateNotLike(Date value) {
            addStockDateCriterion("STOCK_DATE not like", value, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateIn(List<Date> values) {
            addStockDateCriterion("STOCK_DATE in", values, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateNotIn(List<Date> values) {
            addStockDateCriterion("STOCK_DATE not in", values, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateBetween(Date value1, Date value2) {
            addStockDateCriterion("STOCK_DATE between", value1, value2, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateNotBetween(Date value1, Date value2) {
            addStockDateCriterion("STOCK_DATE not between", value1, value2, "stockDate");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqIsNull() {
            addCriterion("STOCK_DATE_SEQ is null");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqIsNotNull() {
            addCriterion("STOCK_DATE_SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqEqualTo(Integer value) {
            addCriterion("STOCK_DATE_SEQ =", value, "stockDateSeq");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqNotEqualTo(Integer value) {
            addCriterion("STOCK_DATE_SEQ <>", value, "stockDateSeq");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqGreaterThan(Integer value) {
            addCriterion("STOCK_DATE_SEQ >", value, "stockDateSeq");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("STOCK_DATE_SEQ >=", value, "stockDateSeq");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqLessThan(Integer value) {
            addCriterion("STOCK_DATE_SEQ <", value, "stockDateSeq");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqLessThanOrEqualTo(Integer value) {
            addCriterion("STOCK_DATE_SEQ <=", value, "stockDateSeq");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqIn(List<Integer> values) {
            addCriterion("STOCK_DATE_SEQ in", values, "stockDateSeq");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqNotIn(List<Integer> values) {
            addCriterion("STOCK_DATE_SEQ not in", values, "stockDateSeq");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqBetween(Integer value1, Integer value2) {
            addCriterion("STOCK_DATE_SEQ between", value1, value2, "stockDateSeq");
            return (Criteria) this;
        }

        public Criteria andStockDateSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("STOCK_DATE_SEQ not between", value1, value2, "stockDateSeq");
            return (Criteria) this;
        }

        public Criteria andPriceOpenIsNull() {
            addCriterion("PRICE_OPEN is null");
            return (Criteria) this;
        }

        public Criteria andPriceOpenIsNotNull() {
            addCriterion("PRICE_OPEN is not null");
            return (Criteria) this;
        }

        public Criteria andPriceOpenEqualTo(Double value) {
            addCriterion("PRICE_OPEN =", value, "priceOpen");
            return (Criteria) this;
        }

        public Criteria andPriceOpenNotEqualTo(Double value) {
            addCriterion("PRICE_OPEN <>", value, "priceOpen");
            return (Criteria) this;
        }

        public Criteria andPriceOpenGreaterThan(Double value) {
            addCriterion("PRICE_OPEN >", value, "priceOpen");
            return (Criteria) this;
        }

        public Criteria andPriceOpenGreaterThanOrEqualTo(Double value) {
            addCriterion("PRICE_OPEN >=", value, "priceOpen");
            return (Criteria) this;
        }

        public Criteria andPriceOpenLessThan(Double value) {
            addCriterion("PRICE_OPEN <", value, "priceOpen");
            return (Criteria) this;
        }

        public Criteria andPriceOpenLessThanOrEqualTo(Double value) {
            addCriterion("PRICE_OPEN <=", value, "priceOpen");
            return (Criteria) this;
        }

        public Criteria andPriceOpenIn(List<Double> values) {
            addCriterion("PRICE_OPEN in", values, "priceOpen");
            return (Criteria) this;
        }

        public Criteria andPriceOpenNotIn(List<Double> values) {
            addCriterion("PRICE_OPEN not in", values, "priceOpen");
            return (Criteria) this;
        }

        public Criteria andPriceOpenBetween(Double value1, Double value2) {
            addCriterion("PRICE_OPEN between", value1, value2, "priceOpen");
            return (Criteria) this;
        }

        public Criteria andPriceOpenNotBetween(Double value1, Double value2) {
            addCriterion("PRICE_OPEN not between", value1, value2, "priceOpen");
            return (Criteria) this;
        }

        public Criteria andPriceClosingIsNull() {
            addCriterion("PRICE_CLOSING is null");
            return (Criteria) this;
        }

        public Criteria andPriceClosingIsNotNull() {
            addCriterion("PRICE_CLOSING is not null");
            return (Criteria) this;
        }

        public Criteria andPriceClosingEqualTo(Double value) {
            addCriterion("PRICE_CLOSING =", value, "priceClosing");
            return (Criteria) this;
        }

        public Criteria andPriceClosingNotEqualTo(Double value) {
            addCriterion("PRICE_CLOSING <>", value, "priceClosing");
            return (Criteria) this;
        }

        public Criteria andPriceClosingGreaterThan(Double value) {
            addCriterion("PRICE_CLOSING >", value, "priceClosing");
            return (Criteria) this;
        }

        public Criteria andPriceClosingGreaterThanOrEqualTo(Double value) {
            addCriterion("PRICE_CLOSING >=", value, "priceClosing");
            return (Criteria) this;
        }

        public Criteria andPriceClosingLessThan(Double value) {
            addCriterion("PRICE_CLOSING <", value, "priceClosing");
            return (Criteria) this;
        }

        public Criteria andPriceClosingLessThanOrEqualTo(Double value) {
            addCriterion("PRICE_CLOSING <=", value, "priceClosing");
            return (Criteria) this;
        }

        public Criteria andPriceClosingIn(List<Double> values) {
            addCriterion("PRICE_CLOSING in", values, "priceClosing");
            return (Criteria) this;
        }

        public Criteria andPriceClosingNotIn(List<Double> values) {
            addCriterion("PRICE_CLOSING not in", values, "priceClosing");
            return (Criteria) this;
        }

        public Criteria andPriceClosingBetween(Double value1, Double value2) {
            addCriterion("PRICE_CLOSING between", value1, value2, "priceClosing");
            return (Criteria) this;
        }

        public Criteria andPriceClosingNotBetween(Double value1, Double value2) {
            addCriterion("PRICE_CLOSING not between", value1, value2, "priceClosing");
            return (Criteria) this;
        }

        public Criteria andPriceHighestIsNull() {
            addCriterion("PRICE_HIGHEST is null");
            return (Criteria) this;
        }

        public Criteria andPriceHighestIsNotNull() {
            addCriterion("PRICE_HIGHEST is not null");
            return (Criteria) this;
        }

        public Criteria andPriceHighestEqualTo(Double value) {
            addCriterion("PRICE_HIGHEST =", value, "priceHighest");
            return (Criteria) this;
        }

        public Criteria andPriceHighestNotEqualTo(Double value) {
            addCriterion("PRICE_HIGHEST <>", value, "priceHighest");
            return (Criteria) this;
        }

        public Criteria andPriceHighestGreaterThan(Double value) {
            addCriterion("PRICE_HIGHEST >", value, "priceHighest");
            return (Criteria) this;
        }

        public Criteria andPriceHighestGreaterThanOrEqualTo(Double value) {
            addCriterion("PRICE_HIGHEST >=", value, "priceHighest");
            return (Criteria) this;
        }

        public Criteria andPriceHighestLessThan(Double value) {
            addCriterion("PRICE_HIGHEST <", value, "priceHighest");
            return (Criteria) this;
        }

        public Criteria andPriceHighestLessThanOrEqualTo(Double value) {
            addCriterion("PRICE_HIGHEST <=", value, "priceHighest");
            return (Criteria) this;
        }

        public Criteria andPriceHighestIn(List<Double> values) {
            addCriterion("PRICE_HIGHEST in", values, "priceHighest");
            return (Criteria) this;
        }

        public Criteria andPriceHighestNotIn(List<Double> values) {
            addCriterion("PRICE_HIGHEST not in", values, "priceHighest");
            return (Criteria) this;
        }

        public Criteria andPriceHighestBetween(Double value1, Double value2) {
            addCriterion("PRICE_HIGHEST between", value1, value2, "priceHighest");
            return (Criteria) this;
        }

        public Criteria andPriceHighestNotBetween(Double value1, Double value2) {
            addCriterion("PRICE_HIGHEST not between", value1, value2, "priceHighest");
            return (Criteria) this;
        }

        public Criteria andPriceLowestIsNull() {
            addCriterion("PRICE_LOWEST is null");
            return (Criteria) this;
        }

        public Criteria andPriceLowestIsNotNull() {
            addCriterion("PRICE_LOWEST is not null");
            return (Criteria) this;
        }

        public Criteria andPriceLowestEqualTo(Double value) {
            addCriterion("PRICE_LOWEST =", value, "priceLowest");
            return (Criteria) this;
        }

        public Criteria andPriceLowestNotEqualTo(Double value) {
            addCriterion("PRICE_LOWEST <>", value, "priceLowest");
            return (Criteria) this;
        }

        public Criteria andPriceLowestGreaterThan(Double value) {
            addCriterion("PRICE_LOWEST >", value, "priceLowest");
            return (Criteria) this;
        }

        public Criteria andPriceLowestGreaterThanOrEqualTo(Double value) {
            addCriterion("PRICE_LOWEST >=", value, "priceLowest");
            return (Criteria) this;
        }

        public Criteria andPriceLowestLessThan(Double value) {
            addCriterion("PRICE_LOWEST <", value, "priceLowest");
            return (Criteria) this;
        }

        public Criteria andPriceLowestLessThanOrEqualTo(Double value) {
            addCriterion("PRICE_LOWEST <=", value, "priceLowest");
            return (Criteria) this;
        }

        public Criteria andPriceLowestIn(List<Double> values) {
            addCriterion("PRICE_LOWEST in", values, "priceLowest");
            return (Criteria) this;
        }

        public Criteria andPriceLowestNotIn(List<Double> values) {
            addCriterion("PRICE_LOWEST not in", values, "priceLowest");
            return (Criteria) this;
        }

        public Criteria andPriceLowestBetween(Double value1, Double value2) {
            addCriterion("PRICE_LOWEST between", value1, value2, "priceLowest");
            return (Criteria) this;
        }

        public Criteria andPriceLowestNotBetween(Double value1, Double value2) {
            addCriterion("PRICE_LOWEST not between", value1, value2, "priceLowest");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNull() {
            addCriterion("VOLUME is null");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNotNull() {
            addCriterion("VOLUME is not null");
            return (Criteria) this;
        }

        public Criteria andVolumeEqualTo(Long value) {
            addCriterion("VOLUME =", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotEqualTo(Long value) {
            addCriterion("VOLUME <>", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThan(Long value) {
            addCriterion("VOLUME >", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThanOrEqualTo(Long value) {
            addCriterion("VOLUME >=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThan(Long value) {
            addCriterion("VOLUME <", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThanOrEqualTo(Long value) {
            addCriterion("VOLUME <=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeIn(List<Long> values) {
            addCriterion("VOLUME in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotIn(List<Long> values) {
            addCriterion("VOLUME not in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeBetween(Long value1, Long value2) {
            addCriterion("VOLUME between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotBetween(Long value1, Long value2) {
            addCriterion("VOLUME not between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("IS_VALID is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("IS_VALID is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Boolean value) {
            addCriterion("IS_VALID =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Boolean value) {
            addCriterion("IS_VALID <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Boolean value) {
            addCriterion("IS_VALID >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_VALID >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Boolean value) {
            addCriterion("IS_VALID <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_VALID <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Boolean> values) {
            addCriterion("IS_VALID in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Boolean> values) {
            addCriterion("IS_VALID not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_VALID between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_VALID not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("LAST_MODIFIED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("LAST_MODIFIED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(Date value) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(Date value) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(Date value) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(Date value) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLike(Date value) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE like", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotLike(Date value) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE not like", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<Date> values) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<Date> values) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
            addLastModifiedDateCriterion("LAST_MODIFIED_DATE not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated do_not_delete_during_merge Mon May 29 11:20:17 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STOCK_PRICE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}