package org.nightang.db.stock.model;

import java.util.Date;

public class StockPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_PRICE.STOCK_NUM
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private String stockNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_PRICE.STOCK_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Date stockDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_PRICE.STOCK_DATE_SEQ
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Integer stockDateSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_PRICE.PRICE_OPEN
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Double priceOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_PRICE.PRICE_CLOSING
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Double priceClosing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_PRICE.PRICE_HIGHEST
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Double priceHighest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_PRICE.PRICE_LOWEST
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Double priceLowest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_PRICE.VOLUME
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Long volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_PRICE.IS_VALID
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Boolean isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_PRICE.LAST_MODIFIED_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Date lastModifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_PRICE.STOCK_NUM
     *
     * @return the value of STOCK_PRICE.STOCK_NUM
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public String getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_PRICE.STOCK_NUM
     *
     * @param stockNum the value for STOCK_PRICE.STOCK_NUM
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setStockNum(String stockNum) {
        this.stockNum = stockNum == null ? null : stockNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_PRICE.STOCK_DATE
     *
     * @return the value of STOCK_PRICE.STOCK_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Date getStockDate() {
        return stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_PRICE.STOCK_DATE
     *
     * @param stockDate the value for STOCK_PRICE.STOCK_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setStockDate(Date stockDate) {
        this.stockDate = stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_PRICE.STOCK_DATE_SEQ
     *
     * @return the value of STOCK_PRICE.STOCK_DATE_SEQ
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Integer getStockDateSeq() {
        return stockDateSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_PRICE.STOCK_DATE_SEQ
     *
     * @param stockDateSeq the value for STOCK_PRICE.STOCK_DATE_SEQ
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setStockDateSeq(Integer stockDateSeq) {
        this.stockDateSeq = stockDateSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_PRICE.PRICE_OPEN
     *
     * @return the value of STOCK_PRICE.PRICE_OPEN
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Double getPriceOpen() {
        return priceOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_PRICE.PRICE_OPEN
     *
     * @param priceOpen the value for STOCK_PRICE.PRICE_OPEN
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setPriceOpen(Double priceOpen) {
        this.priceOpen = priceOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_PRICE.PRICE_CLOSING
     *
     * @return the value of STOCK_PRICE.PRICE_CLOSING
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Double getPriceClosing() {
        return priceClosing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_PRICE.PRICE_CLOSING
     *
     * @param priceClosing the value for STOCK_PRICE.PRICE_CLOSING
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setPriceClosing(Double priceClosing) {
        this.priceClosing = priceClosing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_PRICE.PRICE_HIGHEST
     *
     * @return the value of STOCK_PRICE.PRICE_HIGHEST
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Double getPriceHighest() {
        return priceHighest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_PRICE.PRICE_HIGHEST
     *
     * @param priceHighest the value for STOCK_PRICE.PRICE_HIGHEST
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setPriceHighest(Double priceHighest) {
        this.priceHighest = priceHighest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_PRICE.PRICE_LOWEST
     *
     * @return the value of STOCK_PRICE.PRICE_LOWEST
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Double getPriceLowest() {
        return priceLowest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_PRICE.PRICE_LOWEST
     *
     * @param priceLowest the value for STOCK_PRICE.PRICE_LOWEST
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setPriceLowest(Double priceLowest) {
        this.priceLowest = priceLowest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_PRICE.VOLUME
     *
     * @return the value of STOCK_PRICE.VOLUME
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_PRICE.VOLUME
     *
     * @param volume the value for STOCK_PRICE.VOLUME
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_PRICE.IS_VALID
     *
     * @return the value of STOCK_PRICE.IS_VALID
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_PRICE.IS_VALID
     *
     * @param isValid the value for STOCK_PRICE.IS_VALID
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_PRICE.LAST_MODIFIED_DATE
     *
     * @return the value of STOCK_PRICE.LAST_MODIFIED_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_PRICE.LAST_MODIFIED_DATE
     *
     * @param lastModifiedDate the value for STOCK_PRICE.LAST_MODIFIED_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}