package org.nightang.db.stock.model;

import java.util.Date;

public class StockInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_INFO.STOCK_NUM
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private String stockNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_INFO.ENG_NAME
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private String engName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_INFO.CHI_NAME
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private String chiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_INFO.MKT_CAP
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Long mktCap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_INFO.BOARD_LOT
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Integer boardLot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_INFO.IS_HSI
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Boolean isHsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_INFO.LISTING_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Date listingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_INFO.ACTIVE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STOCK_INFO.LAST_MODIFIED_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    private Date lastModifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_INFO.STOCK_NUM
     *
     * @return the value of STOCK_INFO.STOCK_NUM
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public String getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_INFO.STOCK_NUM
     *
     * @param stockNum the value for STOCK_INFO.STOCK_NUM
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setStockNum(String stockNum) {
        this.stockNum = stockNum == null ? null : stockNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_INFO.ENG_NAME
     *
     * @return the value of STOCK_INFO.ENG_NAME
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_INFO.ENG_NAME
     *
     * @param engName the value for STOCK_INFO.ENG_NAME
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setEngName(String engName) {
        this.engName = engName == null ? null : engName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_INFO.CHI_NAME
     *
     * @return the value of STOCK_INFO.CHI_NAME
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public String getChiName() {
        return chiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_INFO.CHI_NAME
     *
     * @param chiName the value for STOCK_INFO.CHI_NAME
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setChiName(String chiName) {
        this.chiName = chiName == null ? null : chiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_INFO.MKT_CAP
     *
     * @return the value of STOCK_INFO.MKT_CAP
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Long getMktCap() {
        return mktCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_INFO.MKT_CAP
     *
     * @param mktCap the value for STOCK_INFO.MKT_CAP
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setMktCap(Long mktCap) {
        this.mktCap = mktCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_INFO.BOARD_LOT
     *
     * @return the value of STOCK_INFO.BOARD_LOT
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Integer getBoardLot() {
        return boardLot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_INFO.BOARD_LOT
     *
     * @param boardLot the value for STOCK_INFO.BOARD_LOT
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setBoardLot(Integer boardLot) {
        this.boardLot = boardLot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_INFO.IS_HSI
     *
     * @return the value of STOCK_INFO.IS_HSI
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Boolean getIsHsi() {
        return isHsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_INFO.IS_HSI
     *
     * @param isHsi the value for STOCK_INFO.IS_HSI
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setIsHsi(Boolean isHsi) {
        this.isHsi = isHsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_INFO.LISTING_DATE
     *
     * @return the value of STOCK_INFO.LISTING_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Date getListingDate() {
        return listingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_INFO.LISTING_DATE
     *
     * @param listingDate the value for STOCK_INFO.LISTING_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setListingDate(Date listingDate) {
        this.listingDate = listingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_INFO.ACTIVE
     *
     * @return the value of STOCK_INFO.ACTIVE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_INFO.ACTIVE
     *
     * @param active the value for STOCK_INFO.ACTIVE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STOCK_INFO.LAST_MODIFIED_DATE
     *
     * @return the value of STOCK_INFO.LAST_MODIFIED_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STOCK_INFO.LAST_MODIFIED_DATE
     *
     * @param lastModifiedDate the value for STOCK_INFO.LAST_MODIFIED_DATE
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}