package org.nightang.db.stock.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.nightang.db.stock.model.PatternResult;
import org.nightang.db.stock.model.PatternResultExample;

public interface PatternResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATTERN_RESULT
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    long countByExample(PatternResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATTERN_RESULT
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    int deleteByExample(PatternResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATTERN_RESULT
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    int insert(PatternResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATTERN_RESULT
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    int insertSelective(PatternResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATTERN_RESULT
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    List<PatternResult> selectByExample(PatternResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATTERN_RESULT
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") PatternResult record, @Param("example") PatternResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATTERN_RESULT
     *
     * @mbg.generated Mon May 29 11:20:17 CST 2017
     */
    int updateByExample(@Param("record") PatternResult record, @Param("example") PatternResultExample example);
}