package org.nightang.db.stock.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.nightang.db.stock.model.StockInfo;
import org.nightang.db.stock.model.StockInfoExample;

public interface StockInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_INFO
     *
     * @mbg.generated Fri May 26 16:59:24 CST 2017
     */
    long countByExample(StockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_INFO
     *
     * @mbg.generated Fri May 26 16:59:24 CST 2017
     */
    int deleteByExample(StockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_INFO
     *
     * @mbg.generated Fri May 26 16:59:24 CST 2017
     */
    int insert(StockInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_INFO
     *
     * @mbg.generated Fri May 26 16:59:24 CST 2017
     */
    int insertSelective(StockInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_INFO
     *
     * @mbg.generated Fri May 26 16:59:24 CST 2017
     */
    List<StockInfo> selectByExample(StockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_INFO
     *
     * @mbg.generated Fri May 26 16:59:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") StockInfo record, @Param("example") StockInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STOCK_INFO
     *
     * @mbg.generated Fri May 26 16:59:24 CST 2017
     */
    int updateByExample(@Param("record") StockInfo record, @Param("example") StockInfoExample example);
}